server:
  port: 9400
spring:
  application:
    name: admin-server
  boot:
    admin:
      discovery:
        ignored-services: admin-server
eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka