package com.myfarm.core.user.dao;

import com.myfarm.core.user.model.UserProfile;
import com.myfarm.core.user.model.UserProfileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_profile
     *
     * @mbg.generated Wed Apr 14 16:02:16 CST 2021
     */
    long countByExample(UserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_profile
     *
     * @mbg.generated Wed Apr 14 16:02:16 CST 2021
     */
    int deleteByExample(UserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_profile
     *
     * @mbg.generated Wed Apr 14 16:02:16 CST 2021
     */
    int deleteByPrimaryKey(Object userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_profile
     *
     * @mbg.generated Wed Apr 14 16:02:16 CST 2021
     */
    int insert(UserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_profile
     *
     * @mbg.generated Wed Apr 14 16:02:16 CST 2021
     */
    int insertSelective(UserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_profile
     *
     * @mbg.generated Wed Apr 14 16:02:16 CST 2021
     */
    List<UserProfile> selectByExample(UserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_profile
     *
     * @mbg.generated Wed Apr 14 16:02:16 CST 2021
     */
    UserProfile selectByPrimaryKey(Object userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_profile
     *
     * @mbg.generated Wed Apr 14 16:02:16 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserProfile record, @Param("example") UserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_profile
     *
     * @mbg.generated Wed Apr 14 16:02:16 CST 2021
     */
    int updateByExample(@Param("record") UserProfile record, @Param("example") UserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_profile
     *
     * @mbg.generated Wed Apr 14 16:02:16 CST 2021
     */
    int updateByPrimaryKeySelective(UserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_profile
     *
     * @mbg.generated Wed Apr 14 16:02:16 CST 2021
     */
    int updateByPrimaryKey(UserProfile record);
}