server:
  port: 9050
spring:
  application:
    name: ribbon-example
  zipkin:
    base-url: http://localhost:9411
#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
  instance:
    preferIpAddress: true