server:
  port: 8801
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:hi-supergirl/myfarm-config.git
          clone-on-start: true

#eureka
eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka