server:
  port: 8769
spring:
  application:
    name: doc-service
  cloud:
    gateway:
      routes:
        - id: test1_module
          uri: lb://test1-service
          predicates:
            - Path=/test1-service/**
        - id: test2_module
          uri: lb://test2-service
          predicates:
            - Path=/test2-service/**
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写

management:
  endpoints:
    web:
      exposure:
        include: gateway
eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka