package com.myfarm.core.user.model;

import java.util.Date;

public class UserProfile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_profile.user_id
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    private Object userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_profile.name
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_profile.psw
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    private String psw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_profile.telphone
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    private String telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_profile.profile
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    private String profile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_profile.role_id
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    private Object roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_profile.employee_id
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_profile.site_id
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    private Object siteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_profile.create_date
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_profile.update_date
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_profile.user_id
     *
     * @return the value of public.user_profile.user_id
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    public Object getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_profile.user_id
     *
     * @param userId the value for public.user_profile.user_id
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    public void setUserId(Object userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_profile.name
     *
     * @return the value of public.user_profile.name
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_profile.name
     *
     * @param name the value for public.user_profile.name
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_profile.psw
     *
     * @return the value of public.user_profile.psw
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    public String getPsw() {
        return psw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_profile.psw
     *
     * @param psw the value for public.user_profile.psw
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    public void setPsw(String psw) {
        this.psw = psw == null ? null : psw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_profile.telphone
     *
     * @return the value of public.user_profile.telphone
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_profile.telphone
     *
     * @param telphone the value for public.user_profile.telphone
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_profile.profile
     *
     * @return the value of public.user_profile.profile
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    public String getProfile() {
        return profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_profile.profile
     *
     * @param profile the value for public.user_profile.profile
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    public void setProfile(String profile) {
        this.profile = profile == null ? null : profile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_profile.role_id
     *
     * @return the value of public.user_profile.role_id
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    public Object getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_profile.role_id
     *
     * @param roleId the value for public.user_profile.role_id
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    public void setRoleId(Object roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_profile.employee_id
     *
     * @return the value of public.user_profile.employee_id
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_profile.employee_id
     *
     * @param employeeId the value for public.user_profile.employee_id
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_profile.site_id
     *
     * @return the value of public.user_profile.site_id
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    public Object getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_profile.site_id
     *
     * @param siteId the value for public.user_profile.site_id
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    public void setSiteId(Object siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_profile.create_date
     *
     * @return the value of public.user_profile.create_date
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_profile.create_date
     *
     * @param createDate the value for public.user_profile.create_date
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_profile.update_date
     *
     * @return the value of public.user_profile.update_date
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_profile.update_date
     *
     * @param updateDate the value for public.user_profile.update_date
     *
     * @mbg.generated Wed Feb 17 16:26:56 CST 2021
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}